### ISSUE TITLE
Code formatting bug into a input HTML

### ISSUE THREAD

**Issue by vendra95** [aswinkumar863/smarty-vscode-support#127]
**To Reproduce**
An example to reproduce the bug:
create a new file with .tpl extension and write:
`<input type="radio" value="" name="crypto" {if $mail.smtp_crypto==""}checked{/if}> No<br>`

Save and format the file.
The result is :
`<input type="radio" value="" name="crypto" {if $mail.smtp_crypto=="" }checked{/if}> No<br>`

the space between the `""` and `}` is not accepted on template

**Comment by aswinkumar863** [comment]
Related to #9 

Fortunately, I am already working on this along with a major change that expecting to release in the upcoming weeks.

Thanks for reporting.

**Comment by aswinkumar863** [comment]
Resolved in https://github.com/aswinkumar863/smarty-vscode-support/commit/643089630aaff07627f3c965ab25d5b04475c28b. Thank you for your patience.
