### ISSUE TITLE
Support for custom open / close delimiters

### ISSUE THREAD

**Issue by jvalen36** [aswinkumar863/smarty-vscode-support#138]
Hello:

Is there any way to put custon open/close tag instead {} or {{}} ?

regards
jorge

**Comment by aswinkumar863** [comment]
@jvalen36 As of now, there is no way to add custom delimiters.

**Comment by aswinkumar863** [comment]
There is no plan for adding a feature to support custom delimiters now. Some [language features](https://code.visualstudio.com/api/language-extensions/overview#declarative-language-features) like formatting may become more challenging with custom delimiters. Contributions welcome regarding this. Depends on the contribution, I can consider it.

Thanks for opening this.
