### ISSUE TITLE
Settings to define opening and closing delimiters.

### ISSUE THREAD

**Issue by gabriel-peleskei** [aswinkumar863/smarty-vscode-support#283]
Some frameworks use for example "[{" and "}]".

An option to define the delimiters would come in handy.
Jetbrains has this settings:
![smarty](https://user-images.githubusercontent.com/27891270/130963786-db156b08-7567-4db3-aa0d-24f7b3e400f9.jpg)

**Comment by aswinkumar863** [comment]
Duplicate of #138
