### ISSUE TITLE
custom delimiters

### ISSUE THREAD

**Issue by rubenscd-cnds** [aswinkumar863/smarty-vscode-support#302]
the most commonly used traditional delimiters are `{ ... }` and `{{ ... }}` but I would like to be able to set my custom delimiter something like `{! ... }` both opening and closing.

it's possible?

**Comment by dexbol** [comment]
Sadly we have a huge legacy smarty template that use `<{ ... }>` and `<{/ ...}>` as delimiters.

**Comment by aswinkumar863** [comment]
There is no plan for adding a feature to support custom delimiters now. Some [language features](https://code.visualstudio.com/api/language-extensions/overview#declarative-language-features) like formatting may become more challenging with custom delimiters. Contributions are welcome regarding this. Depending on the contribution, I can consider it.

Duplicate #138
