### ISSUE TITLE
May I ask how to make the Smarty Template Support plugin of vscode support the .dwt format, now he only supports the code highlighting and prompts of .tpl

### ISSUE THREAD

**Issue by usertangxin** [aswinkumar863/smarty-vscode-support#328]
May I ask how to make vscode's Smarty Template Support plug-in support the .dwt format? He only supports .tpl code highlighting and prompts, or it already supports it, but I didn't find the setting switch

**Comment by aswinkumar863** [comment]
You can associate `dwt `extensions to `smarty` by adding a [`file.associations`](https://code.visualstudio.com/docs/languages/identifiers) in user [settings.json](https://stackoverflow.com/questions/65908987/vs-code-how-to-open-settings-json-file)

```json
"files.associations": {
    "*.dwt": "smarty"
}
```
