### ISSUE TITLE
Invalid comment toggling inside literal tag

### ISSUE THREAD

**Issue by esemlabel** [aswinkumar863/smarty-vscode-support#329]
**Describe the bug**
When you try to toggle comment inside {literal} tag, for instance, when using with knockout, you will get default smarty block comment {* *} which is treated as regular text. Instead, the comment block should be wrapped in correspoding source format comment like \ for html, or // for js. Or, if it isn't possible to leverage vscode API, just use at least html-style comment being hardcoded as default when using inside literal tag. Besides, previous workaround to edit language-configuration.json::blockComment isn't working anymore and is overridden by /client/out/extension.js.

**To Reproduce**
Toogle block comment inside {literal} tag.

**Screenshots**
<img width="621" alt="image" src="https://user-images.githubusercontent.com/17903845/147119324-79c6bbff-5dca-43ea-8063-5533c6c58b36.png">

**Context (please complete the following information):**
 - Version 1.9.0

**Comment by dgloriaweb** [comment]
Hi, could you sort this out yet? I am trying to override this in vscode to use    instead of {* *}, I've been experimenting adding this to my keybindings.json, but this doesn't work. Thanks.

**Comment by aswinkumar863** [comment]
Code inside `literal` block is always treated as HTML. As proof, you can see Smarty ignores the comment `{* *}` inside the `literal` block. 

So the extension is behaving as predicted.

**Comment by esemlabel** [comment]
You get the issue completely wrong.

The point is that once you toggle the comment (hit the keybinding to add or mark selected text as a comment) inside the literal tag will still put "{*" tags considering the comment is within the smarty layout instead of putting html comment tag "<!--" (or whatever language the document is). This is hardcoded in /client/out/extension.js.
I still think this is invalid behavior of the extension.

Unlike, for instance, built in php extension which toggles "//" and "/*" within "<?php" tag in .php file but once you place php close tag "?>" it will properly use "<!--" since then. Furthermore, starting writing comment in js code inside the same .php file where comment now is considered valid as "<!--", will properly use "//" and "/*" comment pairs instead since these are considered valid for js code.
