### ISSUE TITLE
Add plugin to Open VSX

### ISSUE THREAD

**Issue by JamesCullum** [aswinkumar863/smarty-vscode-support#427]
**Is your feature request related to a problem? Please describe.**
I'm using Visual Studio Code online in Gitpod, which can only install plugins from Open VSX. This plugin is not available there, which means that its not possible to get Smarty syntax highlighting.

**Describe the solution you'd like**
Publish plugin on [Open VSX](https://open-vsx.org/)

**Describe alternatives you've considered**
I could try to publish the plugin as a fork myself

**Comment by JamesCullum** [comment]
Workaround I went for: Forked the project and added the URL to it in the .gitpod.yml, as it also supports URLs. Thats easier than publishing the extension myself on Open VSX.

**Comment by aswinkumar863** [comment]
@JamesCullum Extension published on `open-vsx.org`

https://open-vsx.org/extension/aswinkumar863/smarty-template-support

**Comment by JamesCullum** [comment]
Great, thanks a lot!
