### ISSUE TITLE
Format indent wrong

### ISSUE THREAD

**Issue by Mordef** [aswinkumar863/smarty-vscode-support#5]
Try to format this:
```
{foreach from=$foo item=s}

{if $bar}
{if $bar2}
<div>
    do something
</div>
{/if}
{/if}

{/foreach}
```

Remove ```foreach``` and try again

**Comment by aswinkumar863** [comment]
It doesn't seem like an issue. But feel free to reopen if needed.

**Comment by Mordef** [comment]
nested IF is wrong
When you remove the foreach, then the nesting is fine.

With foreach:
```
{foreach from=$foo item=s}

{if $bar}
{if $bar2}
<div>
    do something
</div>
{/if}
{/if}

{/foreach}
```

and without:
```
{if $bar}
    {if $bar2}
        <div>
            do something
        </div>
    {/if}
{/if}
```
Also wrong when inside block and when extends
More examples:

'extends'
```
{extends file="foo.tpl"}

{if $bar}
{if $bar2}
<div>
    do something
</div>
{/if}
{/if}
```
'block'
```
{block name="foo"}

{if $bar}
{if $bar2}
<div>
    do something
</div>
{/if}
{/if}
{/block}
```

**Comment by aswinkumar863** [comment]
@Mordef Can't reproduce the issue

![Format indent issue](https://user-images.githubusercontent.com/32381261/84236722-bc4c4780-ab15-11ea-9865-7a3c4e325c4b.gif)

**Comment by Mordef** [comment]
![smarty-format-01](https://user-images.githubusercontent.com/22061464/84622701-eae36d00-aedd-11ea-9581-695fb09ce2be.gif)

**Comment by Mordef** [comment]
New
![smarty-format-02](https://user-images.githubusercontent.com/22061464/84622805-3138cc00-aede-11ea-8182-64673205e202.gif)

**Comment by aswinkumar863** [comment]
@Mordef I don't see any issue in master and fixes in new. Trailing spaces on lines 2 and 10 are bad. Happy to see a pull request #10 and #11 but that neither adds a feature nor fixes anything. Please be briefer and responsible for further contributions.

Locking the conversation bcoz of the issue is invalid or not reproducible.
