### ISSUE TITLE
Respect "Wrap Attributes" Setting

### ISSUE THREAD

**Issue by carlson001** [aswinkumar863/smarty-vscode-support#84]
**Is your feature request related to a problem? Please describe.**
When laying out templates, we often like to format our longer HTML tag attributes so they align vertically. In VS Code for regular HTML, the formatter has several options for how "wrapped attributes" (html.format.wrapAttributes) are handled when formatting the document. This can be setup to preserve the way the user likes their HTML to look.

**Describe the solution you'd like**
Allow the Smarty formatter to use the settings the user has already selected for HTML attributes, or add similar options for the Smarty formatter explicitly. 

**Describe alternatives you've considered**
Setting the language to HTML before running Format Document. This is cumbersome, and can lead to the Smarty tags getting mangled in certain cases.

**Comment by aswinkumar863** [comment]
@carlson001 
You may know that there is no formatter available for smarty files. So I decided to use [`js-beautify`](https://github.com/beautify-web/js-beautify) for HTML/CSS/JS. The limitations exist and that is notified [here](https://github.com/aswinkumar863/smarty-vscode-support#known-issues). 

By considering this issue, the "Wrap Attributes" setting may break the smarty tags into new lines. So I disabled that [feature](https://github.com/aswinkumar863/smarty-vscode-support/blob/master/client/src/language/formatter.ts#L97) earlier. While [discussing ](https://github.com/beautify-web/js-beautify/issues/1820) with the js-beautify, they recommended me to add full support for the smarty template. That clearly seems like a new separate project. And I'm sorry, I have no idea of doing that now. I am in searching for an alternative way to achieve this.

I'll keep this issue open for further discussions.

**Comment by bitwiseman** [comment]
@aswinkumar863 
What I recommended was that you make changes to [`templatablepattern.js`](https://github.com/beautify-web/js-beautify/blob/master/js/src/core/templatablepattern.js) to allow the beautifier to recognize smarty template blocks in the same way it recognizes other templating engines.  

Essentially, take the start and end regular expressions you have [here](https://github.com/aswinkumar863/smarty-vscode-support/blob/725ba0b256248a74e439a4bb33f475645716e07c/client/src/language/formatter.ts#L32-L44) and integrate them into `templatablepattern.js`.  This would prevent smarty tags from getting mangled.

**Comment by aswinkumar863** [comment]
Resolved in https://github.com/aswinkumar863/smarty-vscode-support/commit/643089630aaff07627f3c965ab25d5b04475c28b. Thank you @bitwiseman for your support.
