### ISSUE TITLE
Formatting inside <script> tags with smarty code in them

### ISSUE THREAD

**Issue by blaaat** [aswinkumar863/smarty-vscode-support#96]
```
<script>
    {if a}
        b
    {/if}
</script>
```

This code keeps reformatting to something different. Same applies to <style> tags

**Comment by aswinkumar863** [comment]
@blaaat Provided code sample is too minimal to reproduce this issue. You have to check up that any other formatter extension or user setting causing the issue. One way to do is that [disable all installed extension](https://code.visualstudio.com/docs/editor/extension-gallery#:~:text=If%20you%20want%20to%20quickly,until%20you%20re%2Denable%20them.) except Smarty Template Support and [reset the settings.json](https://code.visualstudio.com/docs/getstarted/settings#_how-can-i-reset-my-user-settings) completely. I hope the problem should vanish.

**Comment by aswinkumar863** [comment]
Closing this issue as there is no update from the OP. Please reopen with details about your exact issue if you still experience a problem

**Comment by bitwiseman** [comment]
@aswinkumar863 
You should reopen this issue.
This is the same issue as https://github.com/RiFi2k/format-html-in-php/issues/31 .  If you fix https://github.com/beautify-web/js-beautify/issues/1820, you can make a one line change similar to https://github.com/RiFi2k/format-html-in-php/issues/47 and this will be fixed.
